exclude : ['sass']
google_analytics_id: UA-21369110-4
name: Pierre Baron
navigation:
- text: HOME
  url: /
- text: PROJETS
  url: /works/
  layout: work
- text: BLOG
  url: /blog/
  layout: post
- text: CONTACT
  url: /contact/
markdown: rdiscount
paginate: 5
paginate_path: /blog/page:num
permalink: /blog/:title
pygments: true